name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics-png:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: repositories
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_calendar: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_languages: yes
          config_timezone: America/New_York
          config_output: png
          

  metrics-json:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_calendar: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_languages: yes
          config_timezone: America/New_York
          config_output: json

  metrics-svg:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_calendar: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_languages: yes
          config_timezone: America/New_York

